### ISSUE TITLE
missing linefeed in inline template for type exclude

### ISSUE THREAD

**Issue by eelcomaljaars** [mklauber/puppet-aide#7]
Hi, 

When using your module, the managed aide config file lacks a linefeed for every exclude I defined. Looking at your code, there seems to be missing a linefeed in watch.pp line 17 (https://github.com/mklauber/puppet-aide/blob/develop/manifests/watch.pp#L17)

Could you fix this or would you prefer a PR for this issue? 

Best wishes

**Comment by mklauber** [comment]
I believe I've fixed the issue you've mentioned.  (If I haven't feel free to reopen) However, it's been a couple years since I've been active in puppet module development, so this project is basically unmaintained.  Hopefully the change I made is what you need, and I'll see if I can figure out how to push it to the puppet module library, but no promises.

**Comment by eelcomaljaars** [comment]
Thank for the quick response 👍

**Comment by mklauber** [comment]
Should be on the forge now.
